version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  settings:
    errcheck:
      exclude-functions:
        - io.Closer.Close
        - (*net/http.Response).Body.Close
        - (net/http.ResponseWriter).Write
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - linters:
          - errcheck
        source: "defer.*\\.Close\\(\\)"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/piekstra/slack-cli

run:
  timeout: 5m
